# Generated by Django 5.1.6 on 2025-02-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notehub', '0003_alter_note_author_alter_note_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
