# Generated by Django 5.1.6 on 2025-02-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notehub', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
