# Generated by Django 5.1.6 on 2025-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notehub', '0005_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
